chore: update configuration

diff --git a/script/install-node b/script/install-node
--- a/script/install-node
+++ b/script/install-node
@@ -1,12 +1,14 @@
 #!/bin/bash
 set -e
 
-echo "Installing Node using Volta"
-volta install node@17
-volta install node@lts
+echo "Installing Node using ASDF"
+asdf nodejs update-nodebuild || echo "Failed to update node definitions"
+NODEJS_VERSION=$(asdf nodejs resolve 20 --latest-available)
+asdf install nodejs ${NODEJS_VERSION}
 
-echo "installing a few global npm packages"
-npm install --global serve diff-so-fancy fkill-cli npm-quick-run pnpm
+# asdf install node@20
+NODEJS_LTS_VERSION=$(asdf nodejs resolve lts --latest-available)
+asdf install nodejs ${NODEJS_LTS_VERSION}
 
 echo "Set the default diff utility for Git"
 git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
